---
abstract: 'Emulate Perls internal handling of @INC.'
author:
  - 'Kent Fredric <kentnl@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: '0'
  File::Spec: '0'
  FindBin: '0'
  List::Util: '0'
  Test::Fatal: '0'
  Test::More: '0.98'
  lib: '0'
  perl: '5.008'
configure_requires:
  ExtUtils::MakeMaker: '0'
  perl: '5.008'
dynamic_config: 0
generated_by: 'Dist::Zilla version 6.008, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Path-ScanINC
provides:
  Path::ScanINC:
    file: lib/Path/ScanINC.pm
    version: '1.000003'
recommends:
  Path::Tiny: '0.058'
requires:
  Carp: '0'
  Class::Tiny: '0'
  Data::Dump: '0'
  Path::Tiny: '0'
  Scalar::Util: '0'
  Try::Tiny: '0'
  perl: '5.008'
  strict: '0'
  subs: '0'
  utf8: '0'
  warnings: '0'
resources:
  bugtracker: https://github.com/kentnl/Path-ScanINC/issues
  homepage: https://github.com/kentnl/Path-ScanINC
  repository: https://github.com/kentnl/Path-ScanINC.git
version: '1.000003'
